/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2016-01-27 05:43:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/idpui.tld", Long.valueOf(1366213646000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fidpui_005fserviceName_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fidpui_005fserviceLogo;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fidpui_005fserviceDescription;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fidpui_005fserviceName_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fidpui_005fserviceLogo = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fidpui_005fserviceDescription = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fidpui_005fserviceName_005fnobody.release();
    _005fjspx_005ftagPool_005fidpui_005fserviceLogo.release();
    _005fjspx_005ftagPool_005fidpui_005fserviceDescription.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\" />\n");
      out.write("    <title>Example Login Page</title>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath());
      out.write("/login.css\"/>\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("    <div class=\"wrapper\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <header>\n");
      out.write("          <a class=\"logo\" href=\"../images/dummylogo.png\"><img src=\"");
      out.print( request.getContextPath());
      out.write("/images/dummylogo.png\" alt=\"Replace or remove this logo\"/></a>\n");
      out.write("        </header>\n");
      out.write("    \n");
      out.write("        <div class=\"content\">\n");
      out.write("          <div class=\"column one\">\n");
      out.write("            ");
 if(request.getAttribute("actionUrl") != null){ 
      out.write("\n");
      out.write("              <form id=\"login\" action=\"");
      out.print(request.getAttribute("actionUrl"));
      out.write("\" method=\"post\">\n");
      out.write("            ");
 }else{ 
      out.write("\n");
      out.write("              <form id=\"login\" action=\"j_security_check\" method=\"post\">\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("              ");
 if ("true".equals(request.getAttribute("loginFailed"))) { 
      out.write("\n");
      out.write("                <section>\n");
      out.write("                  <p class=\"form-element form-error\">Login has failed. Double-check your username and password.</p>\n");
      out.write("                </section>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("              <legend>\n");
      out.write("                Log in to ");
      if (_jspx_meth_idpui_005fserviceName_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("              </legend>\n");
      out.write("\n");
      out.write("              <section>\n");
      out.write("                <label for=\"username\">Username</label>\n");
      out.write("                <input class=\"form-element form-field\" name=\"j_username\" type=\"text\" value=\"\">\n");
      out.write("              </section>\n");
      out.write("\n");
      out.write("              <section>\n");
      out.write("                <label for=\"password\">Password</label>\n");
      out.write("                <input class=\"form-element form-field\" name=\"j_password\" type=\"password\" value=\"\">\n");
      out.write("              </section>\n");
      out.write("\n");
      out.write("              <section>\n");
      out.write("                <button class=\"form-element form-button\" type=\"submit\">Login</button>\n");
      out.write("              </section>\n");
      out.write("            </form>\n");
      out.write("            \n");
      out.write("            ");

              //
              //    SP Description & Logo (optional)
              //    These idpui lines will display added information (if available
              //    in the metadata) about the Service Provider (SP) that requested
              //    authentication. These idpui lines are "active" in this example
              //    (not commented out) -- this extra SP info will be displayed.
              //    Remove or comment out these lines to stop the display of the
              //    added SP information.
              //
              //    Documentation: 
              //      https://wiki.shibboleth.net/confluence/display/SHIB2/IdPAuthUserPassLoginPage
              //
              //    Example:
            
      out.write("\n");
      out.write("                    <p>\n");
      out.write("                      ");
      if (_jspx_meth_idpui_005fserviceLogo_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                      ");
      if (_jspx_meth_idpui_005fserviceDescription_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    </p>\n");
      out.write("              \n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"column two\">\n");
      out.write("            <ul class=\"list list-help\">\n");
      out.write("              <li class=\"list-help-item\"><a href=\"#\"><span class=\"item-marker\">&rsaquo;</span> Forgot your password?</a></li>\n");
      out.write("              <li class=\"list-help-item\"><a href=\"#\"><span class=\"item-marker\">&rsaquo;</span> Need Help?</a></li>\n");
      out.write("              <li class=\"list-help-item\"><a href=\"https://wiki.shibboleth.net/confluence/display/SHIB2/IdPAuthUserPassLoginPage\"><span class=\"item-marker\">&rsaquo;</span> How to Customize this Skin</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <footer>\n");
      out.write("        <div class=\"container container-footer\">\n");
      out.write("          <p class=\"footer-text\">Insert your footer text here.</p>\n");
      out.write("        </div>\n");
      out.write("      </footer>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_idpui_005fserviceName_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  idpui:serviceName
    edu.internet2.middleware.shibboleth.idp.ui.ServiceNameTag _jspx_th_idpui_005fserviceName_005f0 = (edu.internet2.middleware.shibboleth.idp.ui.ServiceNameTag) _005fjspx_005ftagPool_005fidpui_005fserviceName_005fnobody.get(edu.internet2.middleware.shibboleth.idp.ui.ServiceNameTag.class);
    _jspx_th_idpui_005fserviceName_005f0.setPageContext(_jspx_page_context);
    _jspx_th_idpui_005fserviceName_005f0.setParent(null);
    int _jspx_eval_idpui_005fserviceName_005f0 = _jspx_th_idpui_005fserviceName_005f0.doStartTag();
    if (_jspx_th_idpui_005fserviceName_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fidpui_005fserviceName_005fnobody.reuse(_jspx_th_idpui_005fserviceName_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fidpui_005fserviceName_005fnobody.reuse(_jspx_th_idpui_005fserviceName_005f0);
    return false;
  }

  private boolean _jspx_meth_idpui_005fserviceLogo_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  idpui:serviceLogo
    edu.internet2.middleware.shibboleth.idp.ui.ServiceLogoTag _jspx_th_idpui_005fserviceLogo_005f0 = (edu.internet2.middleware.shibboleth.idp.ui.ServiceLogoTag) _005fjspx_005ftagPool_005fidpui_005fserviceLogo.get(edu.internet2.middleware.shibboleth.idp.ui.ServiceLogoTag.class);
    _jspx_th_idpui_005fserviceLogo_005f0.setPageContext(_jspx_page_context);
    _jspx_th_idpui_005fserviceLogo_005f0.setParent(null);
    int _jspx_eval_idpui_005fserviceLogo_005f0 = _jspx_th_idpui_005fserviceLogo_005f0.doStartTag();
    if (_jspx_eval_idpui_005fserviceLogo_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_idpui_005fserviceLogo_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_idpui_005fserviceLogo_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_idpui_005fserviceLogo_005f0.doInitBody();
      }
      do {
        out.write("default");
        int evalDoAfterBody = _jspx_th_idpui_005fserviceLogo_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_idpui_005fserviceLogo_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_idpui_005fserviceLogo_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fidpui_005fserviceLogo.reuse(_jspx_th_idpui_005fserviceLogo_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fidpui_005fserviceLogo.reuse(_jspx_th_idpui_005fserviceLogo_005f0);
    return false;
  }

  private boolean _jspx_meth_idpui_005fserviceDescription_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  idpui:serviceDescription
    edu.internet2.middleware.shibboleth.idp.ui.ServiceDescriptionTag _jspx_th_idpui_005fserviceDescription_005f0 = (edu.internet2.middleware.shibboleth.idp.ui.ServiceDescriptionTag) _005fjspx_005ftagPool_005fidpui_005fserviceDescription.get(edu.internet2.middleware.shibboleth.idp.ui.ServiceDescriptionTag.class);
    _jspx_th_idpui_005fserviceDescription_005f0.setPageContext(_jspx_page_context);
    _jspx_th_idpui_005fserviceDescription_005f0.setParent(null);
    int _jspx_eval_idpui_005fserviceDescription_005f0 = _jspx_th_idpui_005fserviceDescription_005f0.doStartTag();
    if (_jspx_eval_idpui_005fserviceDescription_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_idpui_005fserviceDescription_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_idpui_005fserviceDescription_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_idpui_005fserviceDescription_005f0.doInitBody();
      }
      do {
        out.write("SP description");
        int evalDoAfterBody = _jspx_th_idpui_005fserviceDescription_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_idpui_005fserviceDescription_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_idpui_005fserviceDescription_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fidpui_005fserviceDescription.reuse(_jspx_th_idpui_005fserviceDescription_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fidpui_005fserviceDescription.reuse(_jspx_th_idpui_005fserviceDescription_005f0);
    return false;
  }
}
